spring.application.name=food-ordering-system



#database
spring.datasource.url=jdbc:mysql://localhost:3306/food_ordering_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA-Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# Upload config
file.upload-dir=C:\\Users\\DungG\\Downloads\\duandoan\\food-ordering-system\\uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false